modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="All Rights Reserved"
[[mods]] #mandatory
modId="bugging_out" #mandatory
version="1.0.0" #mandatory
displayName="Bugging Out!" #mandatory
#credits="superlord9362, Ralof, hellu_helli" #optional
authors="superlord9362" #optional
description='''
Explore a world where invertabrates rule supreme.
'''
[[dependencies.bugging_out]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${neo_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.bugging_out]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

